#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

cp ../bin/scheduler .
docker build -t ${REPO}/scheduler:${TAG} .

echo Built ${REPO}/scheduler:${TAG}
